[package]
name = "op_rand"
type = "bin"

[dependencies]
ripemd160 = { tag = "v0.0.1", git = "https://github.com/distributed-lab/noir-ripemd160" }
sort = { tag = "v0.2.3", git = "https://github.com/noir-lang/noir_sort" }
